
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  - clang

# before installation
before_install:
      # g++4.8.1
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

      # clang 3.4
      - sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

      - sudo apt-get update -qq
      - sudo pip install --user cpp-coveralls
      - sudo apt-get install -y -qq g++-4.8
      - sudo apt-get install --allow-unauthenticated -qq clang-3.4
      - sudo apt-get install -y lcov
      - gem install coveralls-lcov
      - sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-4.8  90
      - sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-4.8  90
      - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && ./cpp_cache

after_success:
    - cd CMakeFiles/cpp_cache.dir
    - ls
    - lcov --directory . --capture --output-file coverage.info # capture coverage info
    - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
    - lcov --list coverage.info # debug before upload
    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
